garden/apps/introduction/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
import apps.introduction.views as views
# from django.conf.urls import url

app_name='garden'
urlpatterns = [
    path('',views.index,name='introducion'),
    path('contact/',views.contact1,name='contact'),
    path('rules/',views.rules,name='rules'),
    path('rules/ticket/',views.ticket,name='ticket'),
    path('pdf/',views.show_pdf,name='pdf'),
    path('history/',views.history,name='history'),
    re_path(r'^place/(?P<title_place>[-\w]{5,10})/$',views.places,name='place'),
]

garden/garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('garden/',include('apps.introduction.urls',namespace='garden')),
    path('blog/',include('apps.blog.urls',namespace='blog')),
    path('workshop/',include('apps.workshop.urls',namespace='workshop')),
    path('account/',include('apps.accounts.urls',namespace='account')),
    path('memory/',include('apps.memory.urls',namespace='memory')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

garden/apps/introduction/models.py
from django.db import models


class VisitorGroup(models.Model):
    title=models.CharField(verbose_name='عنوان گروه',max_length=50)

    def __str__(self) -> str:
        return f'{self.title}'
    
    class Meta:
        verbose_name='عنوان گروه'
        verbose_name_plural='عنوان گروه ها'
    

class Place(models.Model):
    title=models.CharField(verbose_name='عنوان مکان',max_length=30)
    photo=models.ImageField(upload_to='images/place/',verbose_name='تصویر اصلی')
    visiting_day=models.CharField(max_length=100,verbose_name='روز بازدید')
    visiting_hours=models.CharField(max_length=100,verbose_name='ساعت بازدید')
    rules=models.TextField(verbose_name='قوانین و مقررات')
    more=models.TextField(verbose_name='اطلاعات بیشتر',max_length=3000)
    place_registration_date=models.DateTimeField(verbose_name='تاریخ ثبت مکان',auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.title}'

    class Meta:
        verbose_name='مکان'
        verbose_name_plural="مکان ها"
    
    
class TicketPrice(models.Model):
    visitor_Group_code=models.ForeignKey(VisitorGroup,verbose_name='گروه بازدید کننده',on_delete=models.CASCADE)
    place_code=models.ForeignKey(Place,verbose_name='مکان بازدید',on_delete=models.CASCADE)
    price=models.IntegerField(verbose_name='قیمت',default=0)

    def __str__(self) -> str:
        return f'{self.price}'

    class Meta:
        verbose_name="بلیت"
        verbose_name_plural="بلیت ها"
    
    

class Message(models.Model):
    full_name=models.CharField(verbose_name='نام و نام خانوادگی',max_length=60)
    email=models.EmailField(verbose_name='آدرس ایمیل')
    title_message=models.CharField(verbose_name='موضوع پیغام',max_length=50)
    text=models.TextField(verbose_name='متن پیغام')
    register_date=models.DateTimeField(verbose_name='تاریخ ثبت پیام',auto_now_add=True)
    is_active=models.BooleanField(verbose_name='وضعیت مشاهده پیغام',default=False)
    
    def __str__(self) -> str:
        return f'{self.full_name} {self.title_message} {self.is_active}'

    class Meta:
        verbose_name="پیغام"
        verbose_name_plural="پیغام ها"
    
    

garden/apps/introduction/forms.py
from django import forms
from .models import Message

class contact(forms.ModelForm):
    class Meta:
        model=Message
        fields=['full_name','email','title_message','text']

        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'نام و نام خانوادگی خود را وارد کنید'}),
            'email': forms.EmailInput(attrs={'placeholder': 'مثال : garden@example.com'}),
            'title_message': forms.TextInput(attrs={'placeholder': 'عنوان پیام'}),
            'text': forms.Textarea(attrs={'placeholder': 'متن پیام'}),
        }

garden/apps/introduction/views.py
from django.shortcuts import render
from .models import VisitorGroup,Place,Message,TicketPrice
from django.http import HttpResponse,HttpResponseNotFound,JsonResponse
from django.conf import settings
from .forms import contact
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail,EmailMultiAlternatives


# def SendEmail1(subject, message, to):
#     from_email=settings.EMAIL_HOST_USER
#     send_mail(subject,message,from_email,to)

# def SendEmail2(subject, message, html_contect, to):
#     from_email=settings.EMAIL_HOST_USER
#     send=EmailMultiAlternatives(subject,message,from_email,to)
#     send.attach_alternative(html_contect,'text/html')
#     send.send()


def images(request):
    return {'media':settings.MEDIA_URL,}

    
def index(request):
    return render(request,'introduction/introduction.html')


def is_ajax(request):
    return request.headers.get('X-Requested-With') == 'XMLHttpRequest'

def contact1(request):
    context = {}
    form = contact()
    if request.method == 'POST' and is_ajax(request):
        form = contact(request.POST)
        if form.is_valid():
            try:
                form.save()
                data = form.cleaned_data
                name = data['full_name']
                return JsonResponse({'name': name}, status=200)
            except Exception as e:
                return JsonResponse({'error': 'خطای سرور'}, status=500)
        else:
            errors = form.errors.as_json()
            return JsonResponse({'error': 'خطای نامعتبر بودن فرم'}, status=400)

    context = {'form': form}
    return render(request, 'introduction/contact.html', context)


def rules(request):
    Place1=Place.objects.all()
    
    context={
        "place":Place1,
    }
    return render(request,'introduction/rules.html',context)


def ticket(request):
    Visitor_Group1=VisitorGroup.objects.all()
    Ticket_price1=TicketPrice.objects.all()
    title=Place.objects.all()
    context={
        'ticket':Ticket_price1,
        "group":Visitor_Group1,
    }
    return render(request,'introduction/ticket.html',context)


def show_pdf(request):
    fs=FileSystemStorage()
    file_name='pdf/garden.pdf'
    if fs.exists(file_name):
        with fs.open(file_name) as pdf:
            response=HttpResponse(pdf,content_type='application/pdf')
            response['content-Disposition']='attachment; filename=garden.pdf'
            return response
    else:
        return HttpResponseNotFound('File Not Found...')
    
def history(request):
    return render(request,'introduction/history.html')


def places(request,title_place):
    title_place=title_place.replace('-',' ')
    place=Place.objects.get(title=title_place)
    context={
        'place':place
    }
    return render(request,'introduction/places.html',context)

garden/templates/introduction/contact.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
تماس با ما
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/introduction/contact.css" %}">
    
    <div class="contact-info">
        <h1>اطلاعات تماس</h1>
        <p><a href="m.salkhorde444@gmail.com">m.salkhorde444@gmail.com</a> :ایمیل</p>
        <p>شماره تلفن: <a href="tel:+989011186988">+989011186988</a></p>
        <p>آدرس: استان هرمزگان، شهرستان بستک</p>
    </div>
    <div class="form-box">
        <form method="post" id="contact">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">ارسال</button>
        </form>
    </div>
    <div id="message-box" style="display:none;"></div>
    
    <script type="text/javascript" src="{% static 'js/introduction/contact.js' %}"></script>
    <script type="text/javascript"> var contactUrl = "{% url 'garden:contact' %}"; </script>
{% endblock main %}

garden/templates/introduction/history.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
تاریخچه باغ
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/introduction/history.css" %}">


        <div class="slide-item-vertical">
            <div class="text-content">
                <h1>تاریخچه باغ فردوس</h1>
                <p>باغ فردوس محله‌ای است در شمیران که در نزدیکی خیابان ولیعصر و میدان تجریش واقع شده‌است. اکنون موزه سینمای ایران در این مکان واقع است. از شمال به میدان تجریش و ابتدای خیابان ولیعصر، از جنوب به بزرگراه مدرس و خیابان فرشته، از شرق به خیابان دربندی و انتهای آفریقا و از غرب به خیابان ولیعصر و پل پارک وی محدود می‌گردد. این محله در تهران قدیم وسیع‌تر بوده‌است. از سمت شمال به پل تجریش، از سمت جنوب به پارک وی، از سمت شرق به رودخانه و از سمت غرب به خیابان ولیعصر منتهی شده‌است.[۱] </p>
                <hr>
                <p>به دستور محمدشاه قاجار، در سال ۱۲۶۴ ق، قصری برای او در نزدیکی تجریش ساخته شد؛ اما همزمان با بیماری و مرگ او قصر نیمه‌تمام ماند و وی در همان قصر نیمه‌تمام به نام محمدیه (در محل محمودیه فعلی) از دنیا رفت.
                     همزمان با ساخت قصر محمدیه، درباریان نزدیک به او نیز در همان حوالی اقدام به احداث باغ یا عمارت ییلاقی کردند. از جمله حسینعلی‌خان معیرالممالک باغی احداث کرد که به باغ فردوس مشهور شد. </p>
                
                <hr>
                <p>عمارت باغ فردوس در دو طبقه به سبک قاجاریه و معروف به گوش فیل بنا گذاشته شد. زمین‌های قسمت جنوبی و سراشیبی باغ نیز با سنگ‌چین‌هایی به صورت هفت قطعه مسطح و مطبق درآمد و روی هریک از قطعات، استخری با فواره‌های متعدد احداث شد. استخرها به گونه‌ای ساخته شده بودند که از فواصل دورتر، بزرگ‌تر به نظر می‌آمدند.

                    سپس، دوستعلی‌خان نظام‌الدوله، پسر حسین‌علی‌خان، به همت معماران اصفهانی و یزدی، ساختمانی در قسمت جنوبی باغ برپا کرد و نام آن را رشک بهشت گذاشت. پلکان و بخش‌های دیگری از ساختمان از مرمر اعلای یزد و دیوارهای داخل اتاق با کاغذهای طلایی برجسته پوشانده شده بود؛ اما پسرش دوستمحمدخان معیرالممالک اعتنای چندانی به باغ و ساختمان آن نکرد و با گذشت زمان ساختمان رو به خرابی گذاشت تا حدی که سنگ‌های مرمر آن کنده و به عمارت امیریه (مدرسه‌نظام) برده شد. بعد از آن مالکیت باغ چند بار دست به دست شد تا سرانجام در سال ۱۳۱۸ ق، در زمان سلطنت مظفرالدین شاه قاجار، محمدولی‌خان سپهسالار تنکابنی آن را از ورثه امین‌الملک خرید.
                    
                    سپهسالار، علاوه بر ایجاد فواره و استخرهای مطبق، قنات باغ فردوس را نیز احیا کرد و سر دری با شکوه در مظهر قنات (میدان گاه فعلی باغ فردوس) ساخت؛ ولی به دلیل بدهی به تجارت‌خانه طومانیانس، باغ را به او داد و طومانیانس نیز باغ را در ازای بدهی به دولت رضاخان واگذار کرد. سرانجام در سال ۱۳۱۶ ش، وزارت معارف (آموزش و پرورش) آن‌جا را خرید و ساختمان را مرمت و دبیرستان شاپور تجریش را در آن تأسیس کرد
                    
                    در سال ۱۳۵۰ ساختمان موجود در باغ به مرکز فرهنگی و هنری و نمایشگاهی تبدیل شد و پس از انقلاب نیز در اختیار وزارت فرهنگ و ارشاد اسلامی قرار گرفت.
                    
                    مساحت باغ فردوس ۲۰۰۰۰ متر مربع و طول آن ۲۸۰ متر و شیب آن از شمال غربی به جنوب شرقی است.
                    
                    هم‌چنین، محمود افشار یزدی در سال ۱۳۱۶، قسمتی از باغ و ساختمان اندرونی را که حدود ۶۰۰۰ متر مربع بود، خرید و به تدریج با خریدن قطعات اطراف، مساحت باغ را به ۱۲۰۰۰ متر مربع رسانید. سپس در سال ۱۳۳۷، باغ و ساختمان‌های داخل آن را وقف امور فرهنگی کرد؛ از جمله در سال ۱۳۵۲ قسمتی از آن برای استقرار مؤسسه لغت نامه دهخدا و مؤسسه باستان‌شناسی به دانشگاه تهران واگذار شد که هم‌چنان دایر است. </p>
            </div>
        </div>    
{% endblock main %}

garden/templates/introduction/introduction.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
معرفی باغ
{% endblock my_title %}

{% block main %}
        <link rel="stylesheet" href="{% static "css/introduction/introduction.css" %}">
        
        <div class="introduction-items">
            <h1>معرفی باغ</h1>
            <p>
                <a href="{% url "garden:history" %}">■ تاریخچه</a>
            </p>
            <h1>بخش های باغ</h1>
            <p>
                <select id="menu" name="menu" onchange="goToPage(this)">
                    <option value="">○ صفحه بخش ها</option>
                    <option value="{% url "garden:place" title_place='محوطه' %}">○ صفحه محوطه</option>
                    <option value="{% url "garden:place" title_place='موزه-سینما' %}">○ صفحه موزه سینما</option>
                </select>
            </p>
            <h1>مسیر بازدید</h1>
            <p>
                <a href="{% url "garden:pdf" %}">■ صفحه دانلود</a>
            </p>
            <h1>برنامه و قوانین باغ</h1>
            <p>
                <a href="{% url "garden:rules" %}">○ صفحه اعلام برنامه</a>
            </p>
            <h1>تماس با ما</h1>
            <p>
                <a href="{% url "garden:contact" %}">■ صفحه تماس با ما</a>
            </p>
        </div>

        <script src="{% static "js/introduction/introduction.js" %}"></script>
{% endblock  %}

garden/templates/introduction/places.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
صفحه {{place.title}}
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/introduction/places.css" %}">


        <div class="place">
            <div class="text-content">
                <img src="{{media}}/{{place.photo}}" alt="{{place.title}}" class="img">
                <h1>{{place.title}}</h1>
                <p>
                    <span style="font-weight: bold;">روز بازدید : </span>
                    <span>{{place.visiting_day}}</span>
                </p>
                <p>
                    <span style="font-weight: bold;">ساعت بازدید : </span>
                    <span>{{place.visiting_hours}}</span>
                </p>
                <hr>
                <p>
                    <span style="font-weight: bold; color:#ff6347;">قوانین و مقررات مکان</span>
                    <br>
                    <span>{{place.rules}}</span>
                </p>
                <hr>
                <p>
                    <span style="font-weight: bold; color:#ff6347;">اطلاعات بیشتر</span>
                    <br>
                    <span>{{place.more}}</span>
                </p>
            </div>
        </div>


{% endblock main %}

garden/templates/introduction/rules.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
قوانین و مقررات
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/introduction/rules.css" %}">

            {% for i in place %}
                <div class="place">
                    <img src="{{media}}/{{i.photo}}">
                    <h1 style="color: #ff6347;">{{i.title}}</h1>
                    <h3>ساعت بازدید : {{i.visiting_hours}}</h3>
                    <h3>روز بازدید : {{i.visiting_day}}</h3>
                    <hr>
                    <p style="color: #ff6347; font-weight: bold;">{{i.rules}}</p>
                    <hr>
                    <h3>{{i.more}}</h3>
                    <div>
                        <span style="font-weight: bold;">تاریخ ثبت مکان : </span>
                        <span style="color: #ff6347; font-weight: bold;">{{i.place_registration_date}}</span>
                    </div>
                    <h1>
                        <a href="{% url "garden:ticket" %}" class='ticket'>بهای بلیت</a>
                    </h1>
                </div>
            {% endfor %}

{% endblock main %}

garden/templates/introduction/ticket.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
راهنمای خرید بلیت
{% endblock my_title %}

{% block main %}
<link rel="stylesheet" href="{% static "css/introduction/ticket.css" %}">

    <div class="about-ticket">
        <h1>راهنمای خرید بلیت : </h1>
        <h3>هر بلیت شامل : </h3>
        <p>کد بلیت، نوع گروه بازدید کننده، و قیمت است</p>

        <h3>انواع گروه بازدید کننده : </h3>
        {% for i in group %}
            <p>{{i}}</p>
        {% endfor %}

        <h3>قیمت بلیت برای هر مکان : </h3>
        <p>قیمت بلیت برای هر مکان و با توجه به نوع گروه بازدید کننده متفاوت است</p>
    </div>
    
        <div class="tickets-container">
            {% for i in ticket %}
                <div class="ticket">
                    <h1>کد بلیت : {{i.id}}</h1>
                    <h3>مکان بازدید : {{i.place_code.title}}</h3>
                    <h3>نوع گروه بازدید کننده : {{i.visitor_Group_code}}</h3>
                    <h3>قیمت بلیت : {{i.price}}</h3>
                </div>
            {% endfor %}
        </div>
        
{% endblock main %}