garden/apps/memory/urls.py
from django.urls import path
from .views import *

app_name='memory'
urlpatterns = [
    path('memories/',AllMemory.as_view(),name='index'),
    path('like/',like,name='like'),
    path('removelike/',removelike,name='removelike'),
    path('addmemory/',AddMemory.as_view(),name='addmemory'),
    # path('update/<int:id>/',UpdateMemory.as_view(),name='update'),
]

garden/garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('garden/',include('apps.introduction.urls',namespace='garden')),
    path('blog/',include('apps.blog.urls',namespace='blog')),
    path('workshop/',include('apps.workshop.urls',namespace='workshop')),
    path('account/',include('apps.accounts.urls',namespace='account')),
    path('memory/',include('apps.memory.urls',namespace='memory')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

garden/apps/memory/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

def uploadimage(instance,filename):
    return f'images/memory/{filename}'
class Memory(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user',verbose_name='کاربر')
    title=models.CharField(max_length=200,verbose_name='عنوان خاطره')
    memory_date=models.DateTimeField(verbose_name='تاریخ خاطره',default=timezone.now)
    text=models.TextField(verbose_name='متن خاطره')
    photo=models.ImageField(verbose_name='تصویر اصلی',upload_to=uploadimage)
    register_date=models.DateTimeField(verbose_name='تاریخ ثبت خاطره',auto_now_add=True)
    status=models.BooleanField(verbose_name='وضعیت',default=False)
    
    def __str__(self) -> str:
        return f'{self.title}'

    class Meta:
        verbose_name='خاطره'
        verbose_name_plural="خاطرات"

def uploadimage2(instance,filename):
    return f'images/memory/gallery/{instance.memory.id}/{filename}'
class MemoryGallery(models.Model):
    memory=models.ForeignKey(Memory,on_delete=models.CASCADE,related_name='memory_gallery',verbose_name='خاطره')
    photo=models.ImageField(verbose_name='تصویر',upload_to=uploadimage2)
    
    def __str__(self) -> str:
        return f'{self.memory}'
    
    class Meta:
        verbose_name='تصویر خاطره'
        verbose_name_plural="تصاویر خاطرات"
    
class MemoryLike(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر',related_name='user_like')
    memory=models.ForeignKey(Memory,on_delete=models.CASCADE,verbose_name='خاطره',related_name='memory_like')
    
    def __str__(self) -> str:
        return f'{self.memory}'
    
    class Meta:
        verbose_name='لایک'
        verbose_name_plural="لایک ها"
    

garden/apps/memory/forms.py
from .models import *
from django import forms


class MemoryForm(forms.ModelForm):
    class Meta:
        model=Memory
        fields=['title','text','photo','memory_date']
       
        widgets = {
            'memory_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local',  
            }),
        }
class MemoryGalleryForm(forms.ModelForm):
    class Meta:
        model=MemoryGallery
        fields=['photo']

garden/apps/memory/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from .models import *
from django.http import HttpResponse
from .forms import *
from django.contrib import messages
from django.forms import modelformset_factory

class AllMemory(View):
    def get(self,request,*args,**kwargs):
        memories=Memory.objects.filter(status=True)
        if request.user.is_authenticated:
            list_memory_liked=MemoryLike.objects.filter(user=request.user).values('memory')
            list_memory_liked_id=[memory['memory'] for memory in list_memory_liked]
            return render(request,'memory/index.html',{'memories':memories,"list_memory_liked_id":list_memory_liked_id})
        return render(request,'memory/index.html',{"memories":memories})
    
    
def like(request):
    if request.method=='GET':
        memory_id=request.GET['memory']
        memory=Memory.objects.get(id=memory_id)
        liked=MemoryLike.objects.filter(memory=memory_id,user=request.user)
        if not liked:
            liked=MemoryLike(memory=memory)
            liked.user=request.user
            liked.save()
        return HttpResponse('success')
    return HttpResponse('unsuccess')

def removelike(request):
    if request.method=='GET':
        memory_id=request.GET['memory']
        memory=Memory.objects.get(id=memory_id)
        liked=MemoryLike.objects.filter(memory=memory_id,user=request.user)
        if liked:
            liked.delete()
        return HttpResponse('success')
    return HttpResponse('unsuccess')


class AddMemory(View):
    form_set=modelformset_factory(model=MemoryGallery,form=MemoryGalleryForm,extra=4)
    def get(self,request,*args,**kwargs):
        forms=MemoryForm()
        gallery=self.form_set(queryset=MemoryGallery.objects.none())
        return render(request,'memory/add_memory.html',{'form':forms,'gallery':gallery})
    def post(self,request,*args,**kwargs):
        gallery=self.form_set(request.POST,request.FILES)
        forms=MemoryForm(request.POST,request.FILES)
        if forms.is_valid() and gallery.is_valid():
            cd=forms.cleaned_data
            memory=Memory.objects.create(
                user=request.user,
                title=cd['title'],
                text=cd['text'],
                photo=cd['photo'],
                memory_date=cd['memory_date']
            )

            for form in gallery.cleaned_data:
                if form:
                    MemoryGallery.objects.create(
                        photo=form['photo'],
                        memory=memory
                    )
            messages.success(request,'خاطره با موفقیت درج شد.','success')
            return redirect('main:index')
        else:
            messages.error(request,'اطلاعات وارد شده معتبر نمیباشد.','error')
        return render(request,'memory/add_memory.html',{'form':forms,'gallery':gallery})
    
    
    
    

# بخش اپدیت خاطره غیرفعاله


# class UpdateMemory(View):
#     form_set=modelformset_factory(model=MemoryGallery,form=MemoryGalleryForm,extra=4)
#     def get(self,request,id):
#         memory=Memory.objects.get(id=id)
#         form=MemoryForm()
#         gallery=self.form_set(queryset=MemoryGallery.objects.none())
#         return render(request,'memory/update_memory.html',{'form':form,'memory':memory,'gallery':gallery})
    
#     def post(self,request,id):
#         gallery = self.form_set(request.POST, request.FILES)

#         try:
#             title = request.POST['title']
#             text = request.POST['text']
#             photo = request.FILES.get('photo')  
#             memory_date = request.POST.get('memory_date')  

#             memory = Memory.objects.get(id=id)
#             memory.title = title
#             memory.text = text
#             if photo:  
#                 memory.photo = photo
#             if memory_date:
#                 memory.memory_date = memory_date
#             memory.save()

#             if gallery.is_valid():
#                 for photo in gallery.cleaned_data: 
#                     if photo:
#                         MemoryGallery.objects.create(photo=photo['photo'], memory=memory)

#             messages.success(request, 'خاطره با موفقیت اپدیت شد.', 'success')
#             return redirect('main:index')

#         except Exception as e:
#             print(f'Error occurred: {e}')
#             messages.error(request, 'خطا در بروزرسانی خاطره.', 'error')
#             return redirect('main:index')

garden/templates/memory/add_memory.html
{% extends "main.html" %}
{% load static %}
{% block my_title %}
درج خاطره
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/memory/add_memory.css" %}">

    {% if messages %}
        {% for message in messages %}
            <div class="{{ message.tags }}-message">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}

    <div class="form-box">
        <form method="post" id="memory" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <p class='other-photo-title'>
                <i class="fas fa-arrow-down custom-icon"></i>
                    تصاویر های دیگر
                    <span>(اختیاری)</span>
                <i class="fas fa-arrow-down custom-icon"></i>
            </p>
            {{gallery.management_form}}
            {% for form in gallery %}
                {{form}}
            {% endfor %}
            <button type="submit">ثبت</button>
        </form>
    </div>

{% endblock main %}

garden/templates/memory/index.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
خاطره ها
{% endblock my_title %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/memory/index.css" %}">
    
    <div class="memories-container">
        {% for i in memories %}
            <div class="memory-card">
                <img src="{{ media }}/{{ i.photo }}" alt="{{ i.title }}" class='img'>
                <h1>
                    <span>عنوان خاطره : </span>
                    <span>{{ i.title }}</span>
                </h1>
                <hr>
                <p>
                    <span>متن خاطره : </span>
                    <span>{{ i.text }}</span>
                </p>
                <hr>
                <p class='other-photo-title'>
                    <i class="fas fa-arrow-down custom-icon"></i>
                    عکس های دیگر
                    <i class="fas fa-arrow-down custom-icon"></i>
                </p>
                {% if i.memory_gallery.all %}
                    <div class="gallery">
                        {% for photo in i.memory_gallery.all %}
                                <img src="{{ media }}/{{ photo.photo }}" alt="{{ i.title }}" class='other-photo'>
                        {% endfor %}
                    </div>
                {% else %}
                    <p class='error-message'>هیچ عکسی وجود ندارد</p>
                {% endif %}
                <hr class="hr-for-photo">
                <p>
                    <span>تاریخ خاطره : </span>
                    <span>{{ i.memory_date }}</span>
                </p>
                <hr>
                <p>
                    <span>ثبت شده توسط : </span>
                    <span>{{ i.user }}</span>
                </p>
                
                <span class="heart" data-id="{{ i.id }}" onclick="toggleLike({{ i.id }})">
                    {% if i.id in list_memory_liked_id %}
                        ❤️
                    {% else %}
                        🤍
                    {% endif %}
                </span>  

                {% comment %} برای اپدیت کردن خاطره  {% endcomment %}
                
                {% comment %} {% if user == i.user %}              
                <a href="{% url "memory:update" i.id %}" class='update'>ویرایش</a>
                {% endif %} {% endcomment %}
            </div>
        {% endfor %}

    </div>

    <script>
      
        function toggleLike(id) {
            const heart = $('.heart[data-id="' + id + '"]');
            
            if (heart.html() === '❤️') {
               
                removeLike(id);
            } else {
                
                like(id);
            }
        }

        function like(id) {
            $.ajax({
                type: 'GET',
                url: "{% url 'memory:like' %}",
                data: { memory: id },
                success: function() {
                   
                    $('.heart[data-id="' + id + '"]').html('❤️');
                }
            });
        }

        function removeLike(id) {
            $.ajax({
                type: 'GET',
                url: "{% url 'memory:removelike' %}",
                data: { memory: id },
                success: function() {
                  
                    $('.heart[data-id="' + id + '"]').html('🤍');
                }
            });
        }

    </script>

{% endblock main %}

garden/templates/memory/update_memory.html
{% extends "main.html" %}
{% load static %}

{% block my_title %}
ویرایش خاطره
{% endblock my_title %}

{% comment %} این بخش غیرفعاله {% endcomment %}

{% block main %}
    <link rel="stylesheet" href="{% static "css/memory/add_memory.css" %}">

    <div class='form-box'>
        <form action="" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <p class='warning'>
                ! توجه ! <br>
                <span>تمام اطلاعاتی که قبلا پر کرده اید در سیستم ثبت است و فقط درصورت نیاز به تغییر آن را تغییر دهید.</span>
            </p>
            <p>
                <label for="id_title">عنوان خاطره:</label>
                <input type="text" value="{{ memory.title }}" name='title' id="id_title">
            </p>
            <p>
                <label for="id_text">متن خاطره:</label>
                <textarea name="text" id="id_text" rows="15">{{ memory.text }}</textarea>
            </p>
            <p>
                <label for="id_photo">تصویر اصلی:</label>
                <input type="file" name="photo" accept="image/*" id="id_photo" value="{{ memory.photo }}">
            </p>
            <p>
                <label for="id_memory_date">تاریخ خاطره:</label>
                <input type="datetime-local" name="memory_date" value="{{ memory.memory_date }}" id="id_memory_date">
            </p>
            <p class='other-photo-title'>
                <i class="fas fa-arrow-down custom-icon"></i>
                    تصاویر های دیگر
                    <span>(اختیاری)</span>
                <i class="fas fa-arrow-down custom-icon"></i>
            </p>
            {{gallery.management_form}}
            {% for form1 in gallery %}
                {{form1}}
            {% endfor %}
            <button type="submit">ثبت</button>
        </form>
    </div>
{% endblock main %}