garden/apps/accounts/urls.py
from django.urls import path
from .views import *


app_name='account'
urlpatterns = [
    path('register/',RegisterUserView.as_view(),name='register'),
    path('logout/',LogoutUserView.as_view(),name='logout'),
    path('login/',LoginUserView.as_view(),name='login'),
]

garden/apps/blog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from .views import *


app_name='blog'
urlpatterns = [
    path('',index,name='index'),
    # path('more/',more_blog,name='more'),
    re_path(r'^more/(?P<slug>[-\w\d]+)/(?P<code>[\d]+)/$',more_blog,name='more'),
    path('pdf/<str:file_name>/',show_pdf,name='pdf')
    
]

garden/apps/introduction/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
import apps.introduction.views as views
# from django.conf.urls import url

app_name='garden'
urlpatterns = [
    path('',views.index,name='introducion'),
    path('contact/',views.contact1,name='contact'),
    path('rules/',views.rules,name='rules'),
    path('rules/ticket/',views.ticket,name='ticket'),
    path('pdf/',views.show_pdf,name='pdf'),
    path('history/',views.history,name='history'),
    re_path(r'^place/(?P<title_place>[-\w]{5,10})/$',views.places,name='place'),
]

garden/apps/memory/urls.py
from django.urls import path
from .views import *

app_name='memory'
urlpatterns = [
    path('memories/',AllMemory.as_view(),name='index'),
    path('like/',like,name='like'),
    path('removelike/',removelike,name='removelike'),
    path('addmemory/',AddMemory.as_view(),name='addmemory'),
    # path('update/<int:id>/',UpdateMemory.as_view(),name='update'),
]

garden/garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('garden/',include('apps.introduction.urls',namespace='garden')),
    path('blog/',include('apps.blog.urls',namespace='blog')),
    path('workshop/',include('apps.workshop.urls',namespace='workshop')),
    path('account/',include('apps.accounts.urls',namespace='account')),
    path('memory/',include('apps.memory.urls',namespace='memory')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

garden/templates/partials/footer.html
<footer>
    <p>© 2024 تمامی حقوق محفوظ است.</p>
</footer>

garden/templates/partials/header.html
<header>
    <h1>وب‌سایت باغ فردوس</h1>
</header>

garden/templates/partials/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static "css/partials/navbar.css" %}">

<nav class="main-nav">
    <a href="{% url 'main:index' %}">صفحه اصلی</a>
    <a href="{% url 'garden:introducion' %}">معرفی باغ</a>
    <a href="#">گالری</a>
    <a href="{% url "memory:index" %}">خاطرات بازدید</a>
    {% if user.is_authenticated %}
        <a href="{% url "memory:addmemory" %}">درج خاطره</a>
    {% else %}
        <a href="{% url "account:login" %}" onmouseover="showTooltip1(event)" onmouseout="hideTooltip1()">درج خاطره</a>
    {% endif %}
    <div class="dropdown">
        <a href="#" class="dropbtn dropbtn-special">آموزش و پژوهش <span class="arrow">&#9660;</span></a> 
        <div class="dropdown-content">
            <a href="{% url 'blog:index' %}">مقاله</a>
            <hr> 
            <a href="{% url "workshop:index" %}">کارگاه</a>
        </div>
    </div>
    <a href="{% url 'garden:contact' %}">تماس با ما</a>
    {% if user.is_authenticated %}
        <a href="{% url 'account:logout' %}" class='red-back'>خروج</a>
        {% else %}
        <a href="{% url 'account:login' %}" class='blue-back'>ورود</a>
        <a href="{% url 'account:register' %}" class='green-back'>ثبت نام</a>
    {% endif %}
    <div class='search-box'>
        <form action="/search/" mehtod='get'>
            <input type="text" name="search" id="">
            <button type="submit">جستجو</button>
        
        </form>
    </div>
</nav>

<div id="tooltip1" class="tooltip1">برای درج خاطره اول باید وارد حساب کاربری خود بشید.</div>

<script>
    function showTooltip1(event) {
        var tooltip = document.getElementById("tooltip1");
        tooltip.style.display = "block";
        tooltip.style.left = event.pageX + 10 + "px";
        tooltip.style.top = event.pageY + 10 + "px";
    }

    function hideTooltip1() {
        var tooltip = document.getElementById("tooltip1");
        tooltip.style.display = "none";
    }

    document.addEventListener('mousemove', function(event) {
        var tooltip = document.getElementById("tooltip1");
        if (tooltip.style.display === "block") {
            tooltip.style.left = event.pageX + 10 + "px";
            tooltip.style.top = event.pageY + 10 + "px";
        }
    });
</script>

<style>
    .tooltip1 {
        position: absolute;
        display: none;
        background-color: #333;
        color: white;
        padding: 10px 20px;
        border-radius: 8px;
        font-size: 14px;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        z-index: 1000;
        animation: fadeIn2 0.6s ease-in-out;
        margin: 20px 0;
    }
    
    @keyframes fadeIn2 {
        from { opacity: 0; transform: translateY(-10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    
</style>